### ISSUE TITLE
test for sequence(async generator) fails on clang release build

### ISSUE THREAD

**Issue by luncliff** [luncliff/coroutine#36]
## Note

* Detected: https://github.com/luncliff/coroutine/commit/f9d9b7fbd25f6dd33edf93383bf79d1111939e6b
* Work start: https://github.com/luncliff/coroutine/commit/28eeba3d7c03aa66b5db565c79758b95c83480d6

[Build log from AppVeyor](https://ci.appveyor.com/project/luncliff/coroutine/builds/25801819/job/u0bpx3q8nn2lgkbs)

### Goals

* Fix the test failures in release build
* If that's too hard, make sure of the reason

### Related Issues

* #3  (`channel` test code crash with clang release build)
* #31 (catch2 test crashed on the `sequence`'s test)

### References

* https://bugs.llvm.org/show_bug.cgi?id=40656
* https://www.reddit.com/r/cpp/comments/aoad7l/coroutine_allocation_elision_broken_in_clang_7

**Comment by luncliff** [comment]
https://github.com/luncliff/coroutine/commit/750158b0a8eb0b2c10b2c53bca183cd5538ae379

With Clang 7.1.0, Works on the local machine (WSL Ubuntu 18.04), but it doesn't on the Travis CI Ubuntu 16.04 (Xenial)
```console
luncliff@Sanctuary:~$ clang --version
clang version 7.1.0-svn353565-1~exp1~20190408084827.60 (branches/release_70)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

It's a bit weird ...

**Comment by owt5008137** [comment]
Maybe I found the problem. With clang 6 and apple clang 9. it will generate asm like this:

```asm
movl    $336, %edi                  # imm = 0x150
callq   operator new(unsigned long) # allocate memory for coroutine stack variables
movq    %rax, %r12
# ...
xorps   %xmm0, %xmm0           # initialize coroutine stack variables
movaps  %xmm0, 280(%r12)    # movaps  should use memory address aligned to 16, but 280 % 16 == 8
# ...
```

With clang 7 or upper and apple clang 10 or upper, it will generate the right codes:

```asm
movl    $344, %edi                  # imm = 0x158
callq   operator new(unsigned long) # allocate memory for coroutine stack variables
movq    %rax, %r12
# ...
xorps   %xmm0, %xmm0                # initialize coroutine stack variables
movaps  %xmm0, 288(%rax)            # 288 % 16 == 0
movaps  %xmm0, 272(%rax)
movaps  %xmm0, 256(%rax)
movaps  %xmm0, 240(%rax)
```

This maybe the BUG of compilers.

**Comment by luncliff** [comment]
Appreciate the comment @owt5008137 :D So is the code is from `for co_await`?

I couldn't have much time for C++ recently and forgot most of the codegen issues, but it will be worthy to have a look again for old version.

**Comment by owt5008137** [comment]
@luncliff All of c++20 coroutine functions have this problem.
