### ISSUE TITLE
Webassembly

### ISSUE THREAD

**Issue by unicomp21** [luncliff/coroutine#39]
How hard would it be to make the co_await work on clang 8 and webassembly?

**Comment by luncliff** [comment]
My God! Sorry @unicomp21. I didn't know there was an open issue by another developer.
I'm not familiar with the webasm, so if you have something in mind, please tell me.

**Comment by unicomp21** [comment]
emscripten has the latest asyncify stuff, which is pretty darn nice.
https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html

But, the co_await stuff goes much further with respect to generators, etc.  I'm racking my brain trying to think of how this can be done with least amount of effort, llvm ir to webassembly for coroutines seems to be DOA.  Starting to think qemu for x86 on webassembly might be the fastest path.

**Comment by luncliff** [comment]
Thanks for the link, @unicomp21. At a glance, it will take some time for me to learn about webasm. I think it's quite interesting(and challenging) topic. Let me take a look.

For now, I can't sure it fits for this repo since it can go more than just some example codes.
It would be better to create another repo for it in the case.

**Comment by luncliff** [comment]
God a new reference!

### Reference
* https://github.com/binji/wasm-clang

**Comment by unicomp21** [comment]
Not sure I follow, the above is a webassembly coroutine example?

**Comment by luncliff** [comment]
Sorry @unicomp21.  
To be honest, I couldn't spend time to get about the webasm :(
(Also for this project... I was unable to work on it these months.)

The link is not about the webasm coroutine. I linked it for future reference. (clang + webasm)
