### ISSUE TITLE
yield immediate value?

### ISSUE THREAD

**Issue by CarterLi** [luncliff/coroutine#42]
```c++
coro::enumerable<int> test() {
    co_yield 1;
}
```

```
test.cpp:5:14: error: non-const lvalue reference to type 'coro::enumerable<int>::value_type' (aka 'int') cannot bind to a temporary of type 'int'
    co_yield 1;
             ^
../interface/coroutine/yield.hpp:83:36: note: passing argument to parameter 'ref' here
        auto yield_value(reference ref) noexcept {
```

**Comment by luncliff** [comment]
@CarterLi enumerable should be used with reference.  
Most of generators are allowing `T&&`, but it doesn't.

https://github.com/luncliff/coroutine/blob/5ddc501764ccb77c41ef53657b8c1f2a1cbfcb17/interface/coroutine/yield.hpp#L82-L86

The reason for such restriction is to enforce users to reuse existing variable in the coroutine frame.
For example, the code below is reusing the object `io_task_t task{};`.

https://github.com/luncliff/coroutine/blob/5ddc501764ccb77c41ef53657b8c1f2a1cbfcb17/modules/net/io_linux.cpp#L17-L26

**Comment by CarterLi** [comment]
But it's ugly.

```c++
coro::enumerable<int> test() {
    int i = 1;
    co_yield i;
}
```

**Comment by luncliff** [comment]
Well, indeed I agree with the point. Let me change that. 
But I couldn't work on this project recently and probably the state will remain unchanged for more upcoming weeks... I'm really sorry about that. I will work as soon as possible and let you know.

If you're in an urgent situation, you can try existing generator implementations in https://github.com/Quuxplusone/coro. I strongly recommend those works.
