### ISSUE TITLE
Coroutine build failed with error C7651

### ISSUE THREAD

**Issue by LilyWangL** [luncliff/coroutine#51]
I am a member of Microsoft VCPKG team. In an internal version of Visual Studio, coroutine build failed with error C7651:
```
buildtrees\coroutine\src\1.5.0-36192178c9.clean\modules\portable\frame.cpp(136): error C7651: __builtin_coro_resume cannot be used with /await. Use '/std:c++latest' or later for standard coroutine support
buildtrees\coroutine\src\1.5.0-36192178c9.clean\modules\portable\frame.cpp(144): error C7651: __builtin_coro_destroy cannot be used with /await. Use '/std:c++latest' or later for standard coroutine support
```
This issue due to an internal change in compiler. For fixing this issue, we need to introduce a set of wrapper functions in `frame.cpp` so that the calls to `__builtin_coro_*` only appear in templates with a value-dependent condition. Then in the `portable_coro_(done|resume|destroy)` functions replace the call to `__builtin_coro_*` with a call to the appropriate wrapper with a template `argument <true>`.
I have added a patch to solve this problem temporarily on VCPKG, the related PR https://github.com/microsoft/vcpkg/pull/12456. I submit this issue and want to fix this error on upstream. 

Thanks a lot.

**Comment by luncliff** [comment]
Thanks for let me know!
I will take a look and fix it this weekend.
